# Run on ubuntu
dist: bionic

# Temporarily enable sudo
sudo: true

# Define the language and versions that infoset is written in
language: python
python:
  - 3.6

# Run tests only against the master branch
branches:
  only:
    - master

# Setup services
services:
  - mysql

# Setup global environmental variables
env:
    - PYTHONPATH=./ PATTOO_CONFIGDIR=$HOME/.pattoo-unittests/config PATTOO_TRAVIS=""

# Install PIP packages and create a temporary config file before installing
before_install:
    - pip3 install -r requirements.txt
    - tests/bin/unittest_setup.py
    - mysql -e 'CREATE DATABASE pattoo_unittest;'

before_script: setup/pattoo_installation.py install all

# Run the unittest script
sudo: false
script: tests/bin/do_all_tests.py
