dist: bionic

# Don't use
sudo: true

# Define the language and versions that infoset is written in
language: python
python:
  - 3.6

# Run tests only against the master branch
branches:
  only:
    - master

# Setup services
services:
  - mysql

# Setup global environmental variables
env:
    - PYTHONPATH=./ PATTOO_CONFIGDIR=$HOME/.pattoo-unittests/config PATTOO_TRAVIS=""

# Install PIP packages and create a temporary config file before installing
before_install:
    - pip3 install -r requirements.txt
    - tests/bin/unittest_setup.py
    - mysql -e 'CREATE DATABASE pattoo_unittest;'
    - setup/pattoo_installation.py install all

# Run the unittest scripts
sudo: false
script:
    - python3 -m unittest discover --start tests -- verbose
    - tests/bin/do_all_tests.py
    